name: Release

on:
  release:
    types: [published]

env:
  npm_config_build_from_source: true

jobs:
  build:
    strategy:
      matrix:
        node-version: 16
        os: [ubuntu-20.04, macos-11, windows-2019]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prebuild
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: prebuilds/**/*.node

  build-alpine:
    name: Build on Alpine Linux
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      - name: Install build deps
        run: apk add make g++ python3 git

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prebuild
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: prebuilds/**/*.node

  build-arm:
    name: Build on arm64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: aarch64
            distro: alpine_latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Package artifacts
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          setup: mkdir -p "${PWD}/artifacts"
          dockerRunArgs: --volume "${PWD}:/repo"
          env: |
            npm_config_build_from_source: true
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster)
                apt update -yq
                apt install -yq curl make g++ python
                curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
                apt install -yq nodejs
                npm install --global yarn
                ;;
              alpine*)
                apk add --update make g++ python3
                apk add --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.16/main/ nodejs~=16 npm~=16
                npm install --global yarn
                ;;
            esac
          run: |
            cd /repo
            yarn install --frozen-lockfile
            yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: prebuilds/**/*.node

  build-freebsd:
    name: Build on FreeBSD
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: vmactions/freebsd-vm@v0
        name: Package artifacts
        with:
          envs: "npm_config_build_from_source"
          prepare: |
            pkg install -y gmake python3 yarn-node14
          run: |
            yarn install --frozen-lockfile
            yarn build
          sync: sshfs

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: prebuilds/**/*.node

  publish:
    name: Publish package
    runs-on: ubuntu-20.04
    needs: [build, build-alpine, build-arm, build-freebsd]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish to NPM
        run: yarn publish
        if: ${{ !env.ACT }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
